kind: pipeline
name: docker

steps:
- name: docker
  image: plugins/docker
  settings:
    # dry_run: true
    username: harvzor
    password:
      from_secret: docker_password
    repo: harvzor/portfolio
    auto_tag: true

trigger:
  branch:
  - master
